### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by stephane-r** [derniercri/react-native-redux-i18n#1]
Hello :)

i would like try your module, but i've this error after run `npm start` :

```
Loading dependency graph, done.
Bundling `index.js`  [development, non-minified]  0.0% (0/1), failed.
error: bundling failed: ambiguous resolution: module `/home/user/project/index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/home/user/project/node_modules/react-native-redux-i18n/node_modules/react-native/package.json`
  * `/home/user/project/node_modules/react-native/package.json`
```

I've try to delete `/node_modules/react-native-redux-i18n/node_modules/react-native` folder, but same result.

Do you have any idea for fix this ?

Thank you ;)

**Comment by matthieupinte** [comment]
Hi, did you try any of these (possible) "solutions" :

```
rm -rf node_modules/
npm cache clean
watchman watch-del-all
```

```
npm install -g react-native-git-upgrade
react-native-git-upgrade
```

? @stephane-r

**Comment by m-lg** [comment]
Seems to be tied to an issue with the dependencies in package.json of this module
Moving react-native from "dependencies" to "devDependencies" and "peerDependencies" in a forked version of this project fixed it for me
```
"dependencies": {
    "prop-types": "^15.6.0",
    "react": "^16.0.0",
    "react-native-i18n": "^2.0.8",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2"
  },
  "devDependencies": {
    "react-native": "^0.49.3"
  },
  "peerDependencies": {
    "react-native": "^0.49.3"
  }
```
The version in peer dependencies should be changed to the minimal one, but I don't have the time right now.

**Comment by matthieupinte** [comment]
Hi, I changed the `peerDependencies` in `v1.0.4`, this should do the work... tell me if you still have this issue ;)
