### ISSUE TITLE
What is the different between  react-native-redux-i18n package and redux-react-native-i18n package

### ISSUE THREAD

**Issue by tomzaku** [derniercri/react-native-redux-i18n#5]

**Comment by matthieupinte** [comment]
If you look deeply in the source... `redux-react-native-i18n` use [translatr](https://www.npmjs.com/package/translatr).

Here I'm using `react-native-i18n` that works with `I18n.js`, coupled with `redux`.
It's two different libs for translate... choose wisely... the problem I got with `translatr` it's that I couldn't use **variables**.
