### ISSUE TITLE
Loc not reload when location was changed

### ISSUE THREAD

**Issue by KrivitchenkoRA** [derniercri/react-native-redux-i18n#6]
Hi, I tried to implemen your module and Loc tag didn't reload localized text when user switch between locals. I think you forget one condition in Loc file, when you use method shouldComponentUpdate need add nextProps.locale !== this.props.locale, and all will be fine!
Thanks for you perfect module!

**Comment by matthieupinte** [comment]
Thanks ! It's currently fixed on `v1.0.9`, you can update your package dependency.
Let me know if you have any issues ;)
